# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'stv_project2.3.2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'FMDB/standalone'

  # Pods for stv_project2.3.2

end
